sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get update
  - sudo apt-get install curl
  - rvm install 2.3.1
  - gem install sass
cache:
  directories:
    - node_modules
script: npm test